import type { FastifyInstance } from 'fastify';
import { registerAuthRoutes } from './auth.js';
import { registerIdentityRoutes } from './identity.js';
import { registerSessionsRoutes } from './sessions.js';
import { registerHardeningPolicyRoutes } from './hardening-policy.js';
import { registerHardeningSecurityRoutes } from './hardening-security.js';
import { registerHardeningSyncRoutes } from './hardening-sync.js';
import { registerHardeningConflictRoutes } from './hardening-conflicts.js';
import { registerHardeningJobRoutes } from './hardening-jobs.js';
import { registerHardeningDiagnosticsRoutes } from './hardening-diagnostics.js';
import { registerHardeningProjectionRoutes } from './hardening-projections.js';
import { registerBriefRoutes } from './briefs.js';
import { registerV1HealthRoutes } from './health.js';
import { registerCompanionRoutes } from './companion.js';
import { registerConnectorRoutes } from './connectors.js';
import { registerEventRoutes } from './events.js';
import { registerExportRoutes } from './export.js';
import { registerFeedbackRoutes } from './feedback.js';
import { registerMemoryCorrectionRoutes } from './memory-corrections.js';
import { registerNoteRoutes } from './notes.js';
import { registerObligationRoutes } from './obligations.js';
import { registerPrivacyRoutes } from './privacy.js';
import { registerPolicyDecisionRoutes } from './policy-decisions.js';
import { registerPurgeRoutes } from './purge.js';
import { registerSettingsRoutes } from './settings.js';
import { registerLanguageRoutes } from './languages.js';
import { registerLanguageSettingsRoutes } from './language-settings.js';
import { registerSuggestionRoutes } from './suggestions.js';
import { registerSourceRecordRoutes } from './source-records.js';
import { registerSignalRoutes } from './signals.js';
import { registerMemoryRoutes } from './memory.js';
import { registerPersonRoutes } from './persons.js';
import { registerConversationRoutes } from './conversations.js';
import { registerEntityLinkRoutes } from './entity-links.js';
import { registerContextRoutes } from './context.js';
import { registerPurchaseRoutes } from './purchases.js';
import { registerSubscriptionRoutes } from './subscriptions.js';
import { registerLifeAppointmentRoutes } from './life-appointments.js';
import { registerVoiceRoutes } from './voice.js';
import { registerVoiceCaptureRoutes } from './voice-captures.js';
import { registerProfileRoutes } from './profile.js';
import { registerProfileUprRoutes } from './profile-upr.js';
import { registerReminderRoutes } from './reminders.js';
import { registerAdminSummaryRoutes } from './admin-summary.js';
import { registerPlaceEventRoutes } from './place-events.js';
import { registerPlacesRoutes } from './places.js';
import { registerScreenTimeSummaryRoutes } from './screen-time-summaries.js';
import { registerInsightRoutes } from './insights.js';
import { registerDecisionRoutes } from './decisions.js';
import { registerTaskRoutes } from './tasks.js';
import { registerErrandRoutes } from './errands.js';
import { registerDigitalTwinRoutes } from './digital-twin.js';
import { registerPlanningRoutes } from './planning.js';
import { registerEcosystemRoutes } from './ecosystem.js';
import { registerDeviceRoutes } from './devices.js';
import { registerSurfaceTileRoutes } from './surfaces-tile.js';
import { registerUserStateRoutes } from './user-state.js';
import { registerAssistantRoutes } from './assistant.js';
import { registerGeoContextRoutes } from './geo-context.js';
import { registerRelationshipProfileRoutes } from './relationship-profiles.js';
import { registerLifePhaseRoutes } from './life-phase.js';
import { registerRoutineScaffoldRoutes } from './routine-scaffolds.js';
import { registerCapabilityRoutes } from './capabilities.js';
import { registerDomainRoutes } from './domains.js';
import { registerDocumentRoutes } from './documents.js';
import { registerPrepRoutes } from './prep.js';
import { registerNotificationRoutes } from './notifications.js';
import { registerMobileBriefRoutes } from './mobile-briefs.js';
import { registerMobileCaptureRoutes } from './mobile-capture.js';

export async function registerV1(app: FastifyInstance) {
  await registerV1HealthRoutes(app);
  await registerAuthRoutes(app);
  await registerIdentityRoutes(app);
  await registerSessionsRoutes(app);
  await registerHardeningPolicyRoutes(app);
  await registerHardeningSecurityRoutes(app);
  await registerHardeningSyncRoutes(app);
  await registerHardeningConflictRoutes(app);
  await registerHardeningJobRoutes(app);
  await registerHardeningDiagnosticsRoutes(app);
  await registerHardeningProjectionRoutes(app);
  await registerSettingsRoutes(app);
  await registerLanguageRoutes(app);
  await registerLanguageSettingsRoutes(app);
  await registerPrivacyRoutes(app);
  await registerPolicyDecisionRoutes(app);
  await registerPurgeRoutes(app);
  await registerConnectorRoutes(app);
  await registerSourceRecordRoutes(app);
  await registerSignalRoutes(app);
  await registerMemoryRoutes(app);
  await registerNoteRoutes(app);
  await registerEventRoutes(app);
  await registerPersonRoutes(app);
  await registerConversationRoutes(app);
  await registerEntityLinkRoutes(app);
  await registerContextRoutes(app);
  await registerObligationRoutes(app);
  await registerSuggestionRoutes(app);
  await registerBriefRoutes(app);
  await registerFeedbackRoutes(app);
  await registerMemoryCorrectionRoutes(app);
  await registerCompanionRoutes(app);
  await registerExportRoutes(app);
  await registerPurchaseRoutes(app);
  await registerSubscriptionRoutes(app);
  await registerLifeAppointmentRoutes(app);
  await registerVoiceRoutes(app);
  await registerVoiceCaptureRoutes(app);
  await registerProfileRoutes(app);
  await registerProfileUprRoutes(app);
  await registerReminderRoutes(app);
  await registerAdminSummaryRoutes(app);
  await registerPlacesRoutes(app);
  await registerPlaceEventRoutes(app);
  await registerScreenTimeSummaryRoutes(app);
  await registerInsightRoutes(app);
  await registerDecisionRoutes(app);
  await registerTaskRoutes(app);
  await registerErrandRoutes(app);
  await registerDigitalTwinRoutes(app);
  await registerPlanningRoutes(app);
  await registerEcosystemRoutes(app);
  await registerDeviceRoutes(app);
  await registerSurfaceTileRoutes(app);
  await registerUserStateRoutes(app);
  await registerAssistantRoutes(app);
  await registerGeoContextRoutes(app);
  await registerRelationshipProfileRoutes(app);
  await registerLifePhaseRoutes(app);
  await registerRoutineScaffoldRoutes(app);
  await registerCapabilityRoutes(app);
  await registerDomainRoutes(app);
  await registerDocumentRoutes(app);
  await registerPrepRoutes(app);
  await registerNotificationRoutes(app);
  await registerMobileBriefRoutes(app);
  await registerMobileCaptureRoutes(app);
}
